windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# Workspace 1
windowrule = workspace 1, match:class chromium
windowrule = workspace 1, match:class librewolf
windowrule = workspace 1, match:class firefox

# Workspace 2
windowrule = workspace 2, match:class Alacritty

# Workspace 3
windowrule = workspace 3, match:class org.inkscape.Inkscape
windowrule = workspace 3, match:class org.pwmt.zathura
windowrule = workspace 3, match:class org.kde.okular
windowrule = workspace 3, match:class libreoffice-(.*)
windowrule = workspace 3, match:class pcmanfm
windowrule = workspace 3, match:class com.github.xournalpp.xournalpp

# Workspace 4
windowrule = workspace 4, match:class code

# Workspace 5
windowrule = workspace 5, match:class discord
windowrule = workspace 5, match:class org.telegram.desktop
windowrule = workspace 5, match:class (s|S)ignal

# Workspace 6
windowrule = workspace 6, match:class vlc
windowrule = workspace 6, match:class (.*)rn-Tim(.*)

# Workspace 7
windowrule = workspace 7, match:class org.pulseaudio.pavucontrol
windowrule = workspace 7, match:class nwg-look
windowrule = workspace 7, match:class com.github.FontManager.FontManager
windowrule = workspace 7, match:class qt5ct
windowrule = workspace 7, match:class qt6ct
windowrule = workspace 7, match:class OpenfortiVPN
windowrule = workspace 7, match:title D(b|B)eaver(.*)

# Workspace 8
windowrule = workspace 8, match:title "Spotify Premium"

# Floating rules
windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = size (monitor_w*0.5) (monitor_h*0.5), match:class xdg-desktop-portal-gtk
windowrule = center on, match:class xdg-desktop-portal-gtk
windowrule = float on, match:class blueman-manager
