# Dracula theme colors
background-color = #282A36
prompt-color = #F8F8F2
input-color = #50FA7B
input-background = #44475A
default-result-color = #6272A4
selection-color = #8BE9FD
selection-match-color = #50FA7B
border-color = #6272A4
