# Solarized Light theme colors
background-color = #FDF6E3
prompt-color = #586E75
input-color = #859900
input-background = #EEE8D5
default-result-color = #657B83
selection-color = #268BD2
selection-match-color = #859900
border-color = #93A1A1
